app:
  auth:
    tokenSecret: ENC(B5Oqps/a/gexDFbza7EkeNDAZSyvBeY9CN88D9aapL8ZZw3S5fhJEA==)
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:9000/oauth2/token