server:
  port: 9000


spring:
  #    application:
  #        name:ghostDiary
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(xN+mNulb2NiS4Hz4HPzMrIb8+4b+IB2ccsOSwv7kFENx4rfxfYU0CWQcvIWRAngGBlWTUlTwkJPOMuKWVkOIU0+MnAsgXyuerey5dwAU5V5Ep2TzwE5wecItGeZPZ6Ru)
    username: ENC(hrMkiDRA80v3lH+gTuHlcQ==)
    password: ENC(1K+W1XBeHPsXDVHLqP3z/RlsUuTjxS6U)


jasypt:
  encryptor:
    bean: jasyptStringEncryptor